//! Roc Platform ABI
//!
//! This file defines the Rust interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Usage:
//! 1. Import this module in your platform host
//! 2. Implement each hosted function according to its signature
//! 3. Call `hosted_functions()` to create the dispatch table for RocOps

#![allow(non_camel_case_types, dead_code, unused_imports, clippy::missing_safety_doc)]

use core::ffi::c_void;
use std::alloc::Layout;

/// Type-erased function pointer for hosted function dispatch.
///
/// The second pointer is return storage and the third pointer is the
/// function-specific arguments struct. Roc transfers ownership of
/// refcounted arguments to hosted functions. Hosted functions must
/// decref owned refcounted arguments when done, or transfer that
/// ownership into the return value or longer-lived storage. If the host
/// keeps both the call argument and a stored copy, it must incref the
/// stored copy so each live reference has one ownership.
pub type HostedFn = extern "C" fn(*const RocOps, *mut c_void, *mut c_void);

/// Table of hosted function pointers passed to the Roc runtime.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct HostedFunctions {
    pub count: u32,
    pub fns: *const HostedFn,
}

/// Uniform ABI function pointer stored in `RocErasedCallablePayload`.
pub type RocErasedCallableFn = extern "C" fn(*const RocOps, *mut u8, *const u8, *mut u8);

/// Final-drop callback for inline erased-callable captures.
pub type RocErasedCallableOnDrop = extern "C" fn(*mut u8, *const RocOps);

/// Payload header for `Box(function)`.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct RocErasedCallablePayload {
    pub callable_fn_ptr: RocErasedCallableFn,
    pub on_drop: Option<RocErasedCallableOnDrop>,
}

/// Runtime representation of `Box(function)`.
pub type RocErasedCallable = *mut u8;

pub const ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT: usize = 16;
pub const ROC_ERASED_CALLABLE_CAPTURE_OFFSET: usize =
    (core::mem::size_of::<RocErasedCallablePayload>() + 15) & !15;

#[inline]
pub const fn roc_erased_callable_payload_size(capture_size: usize) -> usize {
    ROC_ERASED_CALLABLE_CAPTURE_OFFSET + capture_size
}

#[inline]
pub unsafe fn roc_erased_callable_payload_ptr(callable: RocErasedCallable) -> *mut RocErasedCallablePayload {
    callable as *mut RocErasedCallablePayload
}

#[inline]
pub unsafe fn roc_erased_callable_capture_ptr(callable: RocErasedCallable) -> *mut u8 {
    callable.add(ROC_ERASED_CALLABLE_CAPTURE_OFFSET)
}

pub unsafe fn roc_erased_callable_allocate(
    roc_ops: &RocOps,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: Option<RocErasedCallableOnDrop>,
    capture_size: usize,
) -> RocErasedCallable {
    let ptr_width = core::mem::size_of::<usize>();
    let alignment = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let extra_bytes = core::cmp::max(ptr_width, ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT);
    let base = roc_ops.alloc(alignment, extra_bytes + roc_erased_callable_payload_size(capture_size)) as *mut u8;
    let data = base.add(extra_bytes);
    let rc = data.sub(core::mem::size_of::<isize>()) as *mut isize;
    *rc = 1;
    let payload = roc_erased_callable_payload_ptr(data);
    *payload = RocErasedCallablePayload { callable_fn_ptr, on_drop };
    data
}

/// Arguments for a Roc allocation request.
#[repr(C)]
#[derive(Debug)]
pub struct RocAlloc {
    pub alignment: usize,
    pub length: usize,
    pub answer: *mut c_void,
}

/// Arguments for a Roc deallocation request.
#[repr(C)]
#[derive(Debug)]
pub struct RocDealloc {
    pub alignment: usize,
    pub ptr: *mut c_void,
}

/// Arguments for a Roc reallocation request.
#[repr(C)]
#[derive(Debug)]
pub struct RocRealloc {
    pub alignment: usize,
    pub new_length: usize,
    pub answer: *mut c_void,
}

/// Arguments for a Roc `dbg` expression.
#[repr(C)]
#[derive(Debug)]
pub struct RocDbg {
    pub utf8_bytes: *mut u8,
    pub len: usize,
}

/// Arguments for a failed Roc `expect`.
#[repr(C)]
#[derive(Debug)]
pub struct RocExpectFailed {
    pub utf8_bytes: *mut u8,
    pub len: usize,
}

/// Arguments for a Roc `crash`.
#[repr(C)]
#[derive(Debug)]
pub struct RocCrashed {
    pub utf8_bytes: *mut u8,
    pub len: usize,
}

/// The operations table passed from the host to the Roc runtime.
#[repr(C)]
pub struct RocOps {
    pub env: *mut c_void,
    pub roc_alloc: extern "C" fn(*mut RocAlloc, *mut c_void),
    pub roc_dealloc: extern "C" fn(*mut RocDealloc, *mut c_void),
    pub roc_realloc: extern "C" fn(*mut RocRealloc, *mut c_void),
    pub roc_dbg: extern "C" fn(*const RocDbg, *mut c_void),
    pub roc_expect_failed: extern "C" fn(*const RocExpectFailed, *mut c_void),
    pub roc_crashed: extern "C" fn(*const RocCrashed, *mut c_void),
    pub hosted_fns: HostedFunctions,
}

impl RocOps {
    /// Allocate memory with the given alignment and length.
    #[inline]
    pub unsafe fn alloc(&self, alignment: usize, length: usize) -> *mut c_void {
        let mut args = RocAlloc {
            alignment,
            length,
            answer: core::ptr::null_mut(),
        };
        (self.roc_alloc)(&mut args, self.env);
        args.answer
    }

    /// Deallocate memory previously allocated with `alloc`.
    #[inline]
    pub unsafe fn dealloc(&self, ptr: *mut c_void, alignment: usize) {
        let mut args = RocDealloc { alignment, ptr };
        (self.roc_dealloc)(&mut args, self.env);
    }

    /// Reallocate memory to a new size.
    #[inline]
    pub unsafe fn realloc(
        &self,
        old_ptr: *mut c_void,
        alignment: usize,
        new_length: usize,
    ) -> *mut c_void {
        let mut args = RocRealloc {
            alignment,
            new_length,
            answer: old_ptr,
        };
        (self.roc_realloc)(&mut args, self.env);
        args.answer
    }
}

/// A Roc string value. Small strings (up to 23 bytes on 64-bit) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `isize::MAX` bytes: about 2 GiB on 32-bit targets and 8 EiB on
/// 64-bit targets.
///
/// This type is ABI-compatible with the Zig RocStr (24 bytes, `#[repr(C)]`).
#[repr(C)]
pub struct RocStr {
    pub bytes: *mut u8,
    pub capacity_or_alloc_ptr: usize,
    pub length: usize,
}

const ROC_STR_SIZE: usize = core::mem::size_of::<RocStr>();
const ROC_SMALL_STR_MAX_LEN: usize = ROC_STR_SIZE - 1;
const ROC_SMALL_STR_BIT: usize = isize::MIN as usize;
const ROC_SEAMLESS_SLICE_TAG: usize = 1;

impl RocStr {
    /// Return an empty RocStr (small string with zero length).
    pub fn empty() -> Self {
        Self {
            bytes: core::ptr::null_mut(),
            capacity_or_alloc_ptr: 0,
            length: ROC_SMALL_STR_BIT,
        }
    }

    /// Return true if this string is stored inline (small string optimization).
    #[inline]
    pub fn is_small_str(&self) -> bool {
        (self.length as isize) < 0
    }

    /// Return true if this string is a seamless slice into another allocation.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        !self.is_small_str() && (self.capacity_or_alloc_ptr & ROC_SEAMLESS_SLICE_TAG) != 0
    }

    /// Return the length of the string in bytes.
    #[inline]
    pub fn len(&self) -> usize {
        if self.is_small_str() {
            let bytes_ptr = self as *const Self as *const u8;
            let last_byte = unsafe { *bytes_ptr.add(ROC_STR_SIZE - 1) };
            (last_byte ^ 0b1000_0000) as usize
        } else {
            self.length
        }
    }

    /// Return true if the string has zero length.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Return the string contents as a byte slice.
    pub fn as_slice(&self) -> &[u8] {
        let ptr = self.as_u8_ptr();
        unsafe { core::slice::from_raw_parts(ptr, self.len()) }
    }

    /// Return a pointer to the raw UTF-8 bytes.
    #[inline]
    pub fn as_u8_ptr(&self) -> *const u8 {
        if self.is_small_str() {
            self as *const Self as *const u8
        } else {
            self.bytes as *const u8
        }
    }

    /// Return the string contents as a `&str`, assuming valid UTF-8.
    pub fn as_str(&self) -> &str {
        // SAFETY: Roc guarantees all strings are valid UTF-8.
        unsafe { core::str::from_utf8_unchecked(self.as_slice()) }
    }

    /// Create a RocStr from a byte slice, using `roc_ops` for heap allocation if needed.
    pub fn from_slice(slice: &[u8], roc_ops: &RocOps) -> Self {
        if slice.len() < ROC_STR_SIZE {
            let mut result = Self::empty();
            let ptr = &mut result as *mut Self as *mut u8;
            unsafe {
                core::ptr::copy_nonoverlapping(slice.as_ptr(), ptr, slice.len());
                *ptr.add(ROC_STR_SIZE - 1) = (slice.len() as u8) | 0b1000_0000;
            }
            result
        } else {
            let ptr_width = core::mem::size_of::<usize>();
            let total = ptr_width + slice.len();
            let base = unsafe { roc_ops.alloc(core::mem::align_of::<usize>(), total) };
            let data_ptr = unsafe { (base as *mut u8).add(ptr_width) };
            // Write refcount = 1
            unsafe {
                let rc = (data_ptr as *mut isize).sub(1);
                *rc = 1;
                core::ptr::copy_nonoverlapping(slice.as_ptr(), data_ptr, slice.len());
            }
            Self {
                bytes: data_ptr,
                capacity_or_alloc_ptr: slice.len() << 1,
                length: slice.len(),
            }
        }
    }

    /// Create a RocStr from a `&str`.
    pub fn from_str(s: &str, roc_ops: &RocOps) -> Self {
        Self::from_slice(s.as_bytes(), roc_ops)
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_ops: &RocOps) {
        if self.is_small_str() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        unsafe {
            let rc = (alloc_ptr as *mut isize).sub(1);
            let prev = *rc;
            if prev == 0 {
                return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            }
            *rc = prev - 1;
            if prev == 1 {
                let ptr_width = core::mem::size_of::<usize>();
                let base = (alloc_ptr as *mut u8).sub(ptr_width) as *mut c_void;
                roc_ops.dealloc(base, core::mem::align_of::<usize>());
            }
        }
    }

    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !ROC_SEAMLESS_SLICE_TAG) as *mut u8
        } else {
            self.bytes
        }
    }
}

impl core::fmt::Debug for RocStr {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RocStr")
            .field("value", &self.as_str())
            .field("len", &self.len())
            .field("is_small", &self.is_small_str())
            .finish()
    }
}

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `ELEMENTS_REFCOUNTED` is true (the default via `RocList<T>`), an extra
/// `ptr_width` bytes are reserved in the allocation header for the element count,
/// matching the Roc runtime's `allocateWithRefcount` layout.
pub type RocList<T> = RocListWith<T, true>;

/// Parameterized list constructor; use `RocList<T>` for refcounted elements.
#[repr(C)]
pub struct RocListWith<T, const ELEMENTS_REFCOUNTED: bool> {
    pub elements: *mut T,
    pub length: usize,
    pub capacity_or_alloc_ptr: usize,
}

impl<T, const ELEMENTS_REFCOUNTED: bool> RocListWith<T, ELEMENTS_REFCOUNTED> {
    #[inline]
    fn header_bytes() -> usize {
        let ptr_width = core::mem::size_of::<usize>();
        let required_space = if ELEMENTS_REFCOUNTED { 2 * ptr_width } else { ptr_width };
        required_space.max(core::mem::align_of::<T>())
    }

    /// Return an empty RocList.
    pub fn empty() -> Self {
        Self {
            elements: core::ptr::null_mut(),
            length: 0,
            capacity_or_alloc_ptr: 0,
        }
    }

    /// Return the number of elements in the list.
    #[inline]
    pub fn len(&self) -> usize {
        self.length
    }

    /// Return true if the list has zero elements.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.length == 0
    }

    /// Return true if this list is a seamless slice into another allocation.
    /// Slices share the rc slot with their backing allocation; the alloc ptr is
    /// encoded in `capacity_or_alloc_ptr` with the low bit set.
    #[inline]
    pub fn is_seamless_slice(&self) -> bool {
        (self.capacity_or_alloc_ptr & 1) != 0
    }

    /// Resolve `self` to the start of its backing allocation (the element block
    /// just after the rc slot). Returns `null` for empty lists. Handles both
    /// whole-backing and seamless-slice forms.
    fn get_allocation_ptr(&self) -> *mut u8 {
        if self.is_seamless_slice() {
            (self.capacity_or_alloc_ptr & !1) as *mut u8
        } else {
            self.elements as *mut u8
        }
    }

    /// Return the list elements as a slice.
    pub fn as_slice(&self) -> &[T] {
        if self.elements.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.elements, self.length) }
        }
    }

    /// Allocate a new list with space for `length` elements.
    pub fn allocate(length: usize, roc_ops: &RocOps) -> Self {
        if length == 0 {
            return Self::empty();
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        let data_bytes = length * core::mem::size_of::<T>();
        let total = data_bytes + header_bytes;
        let base = unsafe { roc_ops.alloc(align, total) };
        let data_ptr = unsafe { (base as *mut u8).add(header_bytes) };
        // Write refcount = 1
        unsafe {
            let rc = (data_ptr as *mut isize).sub(1);
            *rc = 1;
        }
        Self {
            elements: data_ptr as *mut T,
            length,
            capacity_or_alloc_ptr: length << 1,
        }
    }

    /// Create a RocList from a slice, copying elements into a new allocation.
    pub fn from_slice(slice: &[T], roc_ops: &RocOps) -> Self where T: Copy {
        if slice.is_empty() {
            return Self::empty();
        }
        let list = Self::allocate(slice.len(), roc_ops);
        unsafe {
            core::ptr::copy_nonoverlapping(
                slice.as_ptr(),
                list.elements,
                slice.len(),
            );
        }
        list
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(&self, roc_ops: &RocOps) {
        if self.elements.is_null() {
            return;
        }
        let alloc_ptr = self.get_allocation_ptr();
        if alloc_ptr.is_null() {
            return;
        }
        let align = core::mem::align_of::<T>().max(core::mem::align_of::<usize>());
        let header_bytes = Self::header_bytes();
        unsafe {
            let rc = (alloc_ptr as *mut isize).sub(1);
            let prev = *rc;
            if prev == 0 {
                return; // REFCOUNT_STATIC_DATA — elements are in read-only memory
            }
            *rc = prev - 1;
            if prev == 1 {
                let base = alloc_ptr.sub(header_bytes) as *mut c_void;
                roc_ops.dealloc(base, align);
            }
        }
    }
}

impl<T: core::fmt::Debug, const ELEMENTS_REFCOUNTED: bool> core::fmt::Debug for RocListWith<T, ELEMENTS_REFCOUNTED> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.as_slice().iter()).finish()
    }
}

/// Total number of hosted functions in this platform.
pub const HOSTED_FUNCTION_COUNT: u32 = 3;

/// Dispatch index for Stderr.line!.
pub const HOSTED_IDX_STDERR_LINE: u32 = 0;
/// Dispatch index for Stdin.line!.
pub const HOSTED_IDX_STDIN_LINE: u32 = 1;
/// Dispatch index for Stdout.line!.
pub const HOSTED_IDX_STDOUT_LINE: u32 = 2;

/// Tag discriminant for Try.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TryTag {
    Err = 0,
    Ok = 1,
}

/// Tag union: Try
#[repr(C)]
pub struct Try {
    pub payload: TryPayload,
    pub tag: TryTag,
}

#[repr(C)]
pub union TryPayload {
    pub err: core::mem::ManuallyDrop<i32>,
    pub ok: core::mem::ManuallyDrop<()>,
}

const _: () = assert!(core::mem::size_of::<Try>() == 8, "Try size mismatch");
const _: () = assert!(core::mem::align_of::<Try>() == 4, "Try alignment mismatch");

/// Arguments for Stderr.line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
pub struct StderrLineArgs {
    pub arg0: RocStr,
}

/// Arguments for Stdout.line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
#[repr(C)]
pub struct StdoutLineArgs {
    pub arg0: RocStr,
}

/// Implement this struct with your hosted function implementations.
/// Refcounted hosted arguments are owned by the hosted function.
/// Pass it to `hosted_functions()` to create the dispatch table.
pub struct PlatformHostedFns {
    pub stderr_line: extern "C" fn(*const RocOps, *mut c_void, *const StderrLineArgs), // Stderr.line!
    pub stdin_line: extern "C" fn(*const RocOps, *mut RocStr, *mut c_void), // Stdin.line!
    pub stdout_line: extern "C" fn(*const RocOps, *mut c_void, *const StdoutLineArgs), // Stdout.line!
}

/// Create a HostedFunctions dispatch table from your implementations.
///
/// The returned `HostedFunctions` contains a pointer to a leaked heap allocation
/// that lives for the remainder of the program. This is intentional — the dispatch
/// table is typically created once at startup.
///
/// # Safety
/// The function pointers in `fns` must have the correct ABI signatures.
pub fn hosted_functions(fns: &PlatformHostedFns) -> HostedFunctions {
    let ptrs: &'static [HostedFn] = Box::leak(Box::new([
        unsafe { core::mem::transmute(fns.stderr_line as *const ()) }, // Stderr.line! (index 0)
        unsafe { core::mem::transmute(fns.stdin_line as *const ()) }, // Stdin.line! (index 1)
        unsafe { core::mem::transmute(fns.stdout_line as *const ()) }, // Stdout.line! (index 2)
    ]));

    HostedFunctions {
        count: ptrs.len() as u32,
        fns: ptrs.as_ptr(),
    }
}

/// Default memory management functions for Roc platforms.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size (required because `roc_dealloc` does
/// not receive a length parameter).
pub struct DefaultAllocators;

impl DefaultAllocators {
    /// Allocate memory for the Roc runtime using the global allocator.
    pub extern "C" fn roc_alloc(alloc_args: *mut RocAlloc, _env: *mut c_void) {
        unsafe {
            let args = &mut *alloc_args;
            let min_alignment = args.alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;
            let total_size = args.length + size_storage_bytes;

            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            let base_ptr = std::alloc::alloc(layout);
            if base_ptr.is_null() {
                eprintln!("roc_alloc: out of memory");
                std::process::exit(1);
            }

            // Store total size immediately before the user data pointer
            let size_ptr = base_ptr.add(size_storage_bytes).sub(core::mem::size_of::<usize>()) as *mut usize;
            *size_ptr = total_size;

            args.answer = base_ptr.add(size_storage_bytes) as *mut c_void;
        }
    }

    /// Free memory previously allocated by `roc_alloc`.
    pub extern "C" fn roc_dealloc(dealloc_args: *mut RocDealloc, _env: *mut c_void) {
        unsafe {
            let args = &*dealloc_args;
            let min_alignment = args.alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            let size_ptr = (args.ptr as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let total_size = *size_ptr;

            let base_ptr = (args.ptr as *mut u8).sub(size_storage_bytes);
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let layout = Layout::from_size_align_unchecked(total_size, min_alignment);
            std::alloc::dealloc(base_ptr, layout);
        }
    }

    /// Reallocate memory, potentially extending the existing allocation in-place.
    pub extern "C" fn roc_realloc(realloc_args: *mut RocRealloc, _env: *mut c_void) {
        unsafe {
            let args = &mut *realloc_args;
            let min_alignment = args.alignment.max(core::mem::align_of::<usize>());
            let size_storage_bytes = min_alignment;

            // Read old size from metadata
            let old_size_ptr = (args.answer as *const u8).sub(core::mem::size_of::<usize>()) as *const usize;
            let old_total_size = *old_size_ptr;
            let old_base_ptr = (args.answer as *mut u8).sub(size_storage_bytes);

            // Realloc (may extend in-place without copying)
            let new_total_size = args.new_length + size_storage_bytes;
            debug_assert!(min_alignment.is_power_of_two(), "alignment must be a power of two");
            let old_layout = Layout::from_size_align_unchecked(old_total_size, min_alignment);
            let new_base_ptr = std::alloc::realloc(old_base_ptr, old_layout, new_total_size);
            if new_base_ptr.is_null() {
                eprintln!("roc_realloc: out of memory");
                std::process::exit(1);
            }

            // Store new size and return user pointer
            let new_user_ptr = new_base_ptr.add(size_storage_bytes);
            let new_size_ptr = new_user_ptr.sub(core::mem::size_of::<usize>()) as *mut usize;
            *new_size_ptr = new_total_size;
            args.answer = new_user_ptr as *mut c_void;
        }
    }
}

/// Default handlers for dbg, expect-failed, and crash.
///
/// These print to stderr. Suitable for most platform hosts.
pub struct DefaultHandlers;

impl DefaultHandlers {
    /// Print a `dbg` expression to stderr.
    pub extern "C" fn roc_dbg(dbg_args: *const RocDbg, _env: *mut c_void) {
        unsafe {
            let args = &*dbg_args;
            let msg = core::slice::from_raw_parts(args.utf8_bytes, args.len);
            // SAFETY: Roc guarantees all strings are valid UTF-8.
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("\x1b[36m[ROC DBG]\x1b[0m {}", msg);
        }
    }

    /// Print a failed `expect` to stderr.
    pub extern "C" fn roc_expect_failed(expect_args: *const RocExpectFailed, _env: *mut c_void) {
        unsafe {
            let args = &*expect_args;
            let msg = core::slice::from_raw_parts(args.utf8_bytes, args.len);
            // SAFETY: Roc guarantees all strings are valid UTF-8.
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("\x1b[33m[ROC EXPECT]\x1b[0m {}", msg);
        }
    }

    /// Print a `crash` message to stderr and exit.
    pub extern "C" fn roc_crashed(crash_args: *const RocCrashed, _env: *mut c_void) {
        unsafe {
            let args = &*crash_args;
            let msg = core::slice::from_raw_parts(args.utf8_bytes, args.len);
            // SAFETY: Roc guarantees all strings are valid UTF-8.
            let msg = core::str::from_utf8_unchecked(msg);
            eprintln!("\x1b[31m[ROC CRASHED]\x1b[0m {}", msg);
            std::process::exit(1);
        }
    }
}

/// Create a RocOps struct with default memory management and error handlers.
///
/// This is a convenience function that wires together `DefaultAllocators`,
/// `DefaultHandlers`, and the provided hosted functions into a ready-to-use `RocOps`.
///
/// # Arguments
///
/// * `env` - A pointer to your host environment (or null if unused)
/// * `hosted_fns` - The hosted function dispatch table from `hosted_functions()`
///
/// # Example
///
/// ```ignore
/// let roc_ops = make_roc_ops(core::ptr::null_mut(), hosted_functions(&fns));
/// ```
pub fn make_roc_ops(env: *mut c_void, hosted_fns: HostedFunctions) -> RocOps {
    RocOps {
        env,
        roc_alloc: DefaultAllocators::roc_alloc,
        roc_dealloc: DefaultAllocators::roc_dealloc,
        roc_realloc: DefaultAllocators::roc_realloc,
        roc_dbg: DefaultHandlers::roc_dbg,
        roc_expect_failed: DefaultHandlers::roc_expect_failed,
        roc_crashed: DefaultHandlers::roc_crashed,
        hosted_fns,
    }
}
