on:
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-nix:
    strategy:
      fail-fast: false
      matrix:
        # macos-13 uses x86-64 machine, macos-14 uses aarch64
        # I just use ubuntu here, as I run apple silicon mac locally so no need to test it here
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # install nix
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v12
        with:
          name: enigmaticsunrise
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: print architecture
        run: uname -m

      - name: Build platform prebuilt hosts
        run: nix develop -c sh -c 'roc ./build.roc'

      - name: Run all tests
        run: nix develop -c sh -c 'export ROC=roc && export EXAMPLES_DIR=./examples/ && ./ci/all_tests.sh'
