name: Nightly configuration
on:
  pull_request:
  workflow_dispatch:
    inputs:
      nightly_validation:
        description: Validate a nightly candidate
        type: boolean
        default: false
permissions:
  contents: read
jobs:
  configuration:
    uses: lukewilliamboswell/roc-automation/.github/workflows/check-config.yml@b60d561cbd53c911b29238b30624827f8487113a
